//  SIDER
const SIDER_WIDTH = 168
const HEADER_HEIGHT = 64
const ICON_TOP_MARGIN_FIX = 6
const DEFAULT_ACTION_COLUMN_WIDTH = 90

export {
  SIDER_WIDTH,
  HEADER_HEIGHT,
  ICON_TOP_MARGIN_FIX,
  DEFAULT_ACTION_COLUMN_WIDTH,
}
