import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Person from 'models/Person'
import { Button } from 'antd'

export default function Home() {
  const person: Person = { name: "Mehmet", surname: "Yılmaz" }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Button type="primary">Button</Button>
        <div className={styles.center}>
          {person.name}
        </div>
      </main>
    </>
  )
}